server:
  tomcat:
    max-swallow-size : 100MB
  port: 8080
  servlet:
      context-path: /api/v1/
spring:
  application:
    name: AssetManagement
  datasource:
    url: jdbc:mariadb://localhost:3306/asm
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql